########################################################## OLD .ENV #############################################################

# CORE
#AUTH_URL="https://auth.dolphinsistemas.com.br/realms/dealercrm/protocol/openid-connect/token"
#INTERVAL=1
#THROTTLE=0

# PRODUÇÃO #
#CONTEXT_GUID="230c9229-6d54-11f0-9e58-c695cae6e357"
#CLIENT_ID="kronospet-auth-1761226113054"
#CLIENT_SECRET="l_Y-pWvi1seJ0Q-n3xI6Evh7fJT5cmJdmrO8PIdXq0t"
#API_URL="https://api-kronospet.dealercrm.com.br"
#CRM_URL="https://kronospet.dealercrm.com.br"

# TREINO #
#CONTEXT_GUID="af1a5eb4-6d54-11f0-8ce7-baccb1227f9a"
#CLIENT_ID="treino-kronospet-1778695296950"
#CLIENT_SECRET="K74VIJ6QgmqIY5IaSJ5ThjYvn2yvxbl0sinbxNyQeRX"
#API_URL="https://api-treino-kronospet.dealercrm.com.br"
#CRM_URL="https://treino-kronospet.dealercrm.com.br"

########################################################## APP CONFIG ###########################################################

[config]
auth_url = "https://auth.dolphinsistemas.com.br/realms/dealercrm/protocol/openid-connect/token"
api_url = "https://api-treino-kronospet.dealercrm.com.br"
crm_url = "https://treino-kronospet.dealercrm.com.br"
client_id = "treino-kronospet-1778695296950"
client_secret = "K74VIJ6QgmqIY5IaSJ5ThjYvn2yvxbl0sinbxNyQeRX"
context_guid = "af1a5eb4-6d54-11f0-8ce7-baccb1227f9a"
interval = 5
throttle = 5

[config.mysql]
user = "eusebio"
password = "4kH@0go0j!DvracO"
host = "177.70.19.93"
port = "30108"
database = "Dealer_Kronospet_Treino"

[config.oracle]
user = "KRONOS"
password = "LARANJA"
host = "172.20.92.10"
port = "1521"
database = "TESTE"

########################################################## MOGI MIRIM ###########################################################
[company.mogi_mirim]
code = 100

[company.mogi_mirim.columns.pedido_em_carteira]
code = 211
name = "PEDIDO EM CARTEIRA"
responsible = "paulo"

[company.mogi_mirim.columns.producao]
code = 205
name = "PRODUCAO"
responsible = "paulo"

[company.mogi_mirim.columns.empenho]
code = 212
name = "EMPENHO"
responsible = "comercial"

[company.mogi_mirim.columns.ordem_separacao]
code = 209
name = "ORDEM SEPARACAO"
responsible = "felipe"

[company.mogi_mirim.columns.separacao]
code = 210
name = "SEPARACAO"
responsible = "felipe"

[company.mogi_mirim.columns.faturamento]
code = 206
name = "FATURAMENTO"
responsible = "cristiane"

[company.mogi_mirim.columns.qualidade]
code = 215
name = "QUALIDADE"
responsible = "maria"

[company.mogi_mirim.columns.coleta]
code = 216
name = "COLETA"
responsible = "diego"

[company.mogi_mirim.columns.carregamento]
code = 214
name = "CARREGAMENTO"
responsible = "diego"

[company.mogi_mirim.columns.em_transito]
code = 213
name = "EM TRANSITO"
responsible = "diego"

[company.mogi_mirim.columns.canhoto]
code = 217
name = "CANHOTO"
responsible = "diego"

[company.mogi_mirim.columns.pedido_cancelado]
code = 208
name = "PEDIDO CANCELADO"
responsible = "comercial"

[company.mogi_mirim.columns.finalizado]
code = 207
name = "FINALIZADO"
responsible = "comercial"

[company.mogi_mirim.users.paulo]
code = 10
name = "Paulo"

[company.mogi_mirim.users.felipe]
code = 16
name = "Felipe"

[company.mogi_mirim.users.maicon]
code = 18
name = "Maicon"

[company.mogi_mirim.users.diego]
code = 20
name = "Diego"

[company.mogi_mirim.users.maria]
code = 22
name = "Maria"

[company.mogi_mirim.users.cristiane]
code = 4
name = "Cris"

[company.mogi_mirim.users.comercial]
code = 999
name = "comercial"

[company.mogi_mirim.columns.separacao.product_override]
PREFORMA = "felipe"
FRASCO = "maicon"

########################################################## JACUTINGA ###########################################################

[company.jacutinga]
code = 110

[company.jacutinga.columns.pedido_em_carteira]
code = 84
name = "PEDIDO EM CARTEIRA"
responsible = "thiago"

[company.jacutinga.users.thiago]
code = 4666
name = "Thiago"

[company.jacutinga.users.comercial]
code = 999
name = "comercial"

########################################################## MARINGA ##############################################################

[company.maringa]
code = 120

[company.maringa.columns.pedido_em_carteira]
code = 178
name = "PEDIDO EM CARTEIRA"
responsible = "andre"

[company.maringa.users.andre]
code = 4686
name = "Andre"

[company.maringa.users.comercial]
code = 999
name = "comercial"

########################################################## VENDEDORES ###########################################################

[requesters.a_cutri]
code = 5
name = "A.CUTRI"

[requesters.t_moreira]
code = 6
name = "T.MOREIRA"

[requesters.m_moraes]
code = 7
name = "M.MORAES"

[requesters.a_mendes]
code = 8
name = "A.MENDES"

[requesters.p_migliari]
code = 9
name = "P.MIGLIARI"


[requesters.default]
code = 4688
name = "DEFAULT"
